# Generated by Django 4.0.3 on 2022-03-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0002_remove_loginlogoutlog_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlogoutlog',
            name='host',
        ),
    ]
