# Generated by Django 4.0.3 on 2022-03-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
