# Generated by Django 4.0.3 on 2022-03-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0006_cuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
