# Generated by Django 4.0.3 on 2022-03-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0009_cuenta_created_cuenta_updated'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginlogoutlog',
            table='Entradas y Salidas',
        ),
    ]
