# Generated by Django 4.0.3 on 2022-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0015_delete_propuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital', models.CharField(choices=[('Ninguna me convence', 'Ninguna me convence'), ('Bajar VT', 'Bajar VT'), ('Bajar PEEP', 'Bajer PEEP'), ('Bajar RR', 'Bajar RR')], max_length=25)),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
        ),
        migrations.AlterField(
            model_name='mapas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
