# Generated by Django 4.0.3 on 2022-03-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0016_propuestas_alter_mapas_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapas',
        ),
    ]
