# Generated by Django 4.0.3 on 2022-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0017_delete_mapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('centro', models.CharField(max_length=2)),
                ('servicio', models.CharField(max_length=4)),
                ('hab', models.CharField(max_length=5)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.FloatField(null=True)),
                ('mp', models.FloatField(null=True)),
                ('vt', models.FloatField(null=True)),
                ('peep', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('pplato', models.FloatField(null=True)),
                ('ppeak', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
            },
        ),
    ]
