# Generated by Django 4.0.3 on 2022-03-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0018_mapas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapas',
        ),
    ]
