# Generated by Django 4.0.3 on 2022-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0019_delete_mapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('Centro', models.CharField(choices=[('JX', 'JX'), ('VH', 'VH')], max_length=15)),
                ('Servicio', models.CharField(choices=[('UCI1', 'UCI1'), ('UCI2', 'UCI2'), ('UCIA', 'UCIA'), ('UCIP', 'UCIP'), ('UCIN', 'UCIN')], max_length=15)),
                ('Habitacion', models.CharField(choices=[('BOX01', 'BOX01'), ('BOX02', 'BOX02')], max_length=15)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paciente', models.FloatField(null=True)),
                ('MP', models.FloatField(null=True)),
                ('VT', models.FloatField(null=True)),
                ('PEEP', models.FloatField(null=True)),
                ('RR', models.FloatField(null=True)),
                ('PPlato', models.FloatField(null=True)),
                ('PPeak', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
            },
        ),
    ]
