# Generated by Django 4.0.3 on 2022-03-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0020_mapas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLogoutLog',
        ),
    ]
