# Generated by Django 4.0.3 on 2022-03-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0023_rename_hospital_propuestas_opciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapas',
            name='Paciente',
        ),
    ]
