# Generated by Django 4.0.3 on 2022-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0025_alter_mapas_centro_alter_mapas_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vista de pagina'),
        ),
    ]
