# Generated by Django 4.0.3 on 2022-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0026_mapas_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='propuestas',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
