# Generated by Django 4.0.3 on 2022-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0028_centros_remove_mapas_centro_mapas_centro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapas',
            name='Centro',
        ),
        migrations.AddField(
            model_name='mapas',
            name='Centros',
            field=models.CharField(blank=True, choices=[('VH', 'VH'), ('JX', 'JX')], max_length=15, verbose_name='Servicio'),
        ),
        migrations.DeleteModel(
            name='Centros',
        ),
    ]
