# Generated by Django 4.0.3 on 2022-03-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0029_remove_mapas_centro_mapas_centros_delete_centros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('mapas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='UCI_App.mapas')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('opciones', models.CharField(choices=[('Ninguna me convence', 'Ninguna me convence'), ('Bajar VT', 'Bajar VT'), ('Bajar PEEP', 'Bajer PEEP'), ('Bajar RR', 'Bajar RR')], max_length=25)),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
            bases=('UCI_App.mapas',),
        ),
        migrations.DeleteModel(
            name='Propuestas',
        ),
    ]
