# Generated by Django 4.0.3 on 2022-03-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0031_propuestas_delete_propuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuemtas'},
        ),
        migrations.RemoveField(
            model_name='loginlogoutlog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='loginlogoutlog',
            name='updated',
        ),
    ]
