# Generated by Django 4.0.3 on 2022-03-10 17:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0032_alter_cuenta_options_remove_loginlogoutlog_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='ID'),
        ),
    ]
