# Generated by Django 4.0.3 on 2022-03-10 17:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0033_mapas_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.RemoveField(
            model_name='mapas',
            name='views',
        ),
        migrations.AlterField(
            model_name='mapas',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='Habitacion'),
        ),
    ]
