# Generated by Django 4.0.3 on 2022-03-10 18:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0037_remove_mapas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapeo',
            fields=[
                ('titulo', models.CharField(max_length=25)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='ID')),
                ('Centros', models.CharField(blank=True, choices=[('VH', 'VH'), ('JX', 'JX')], max_length=15, verbose_name='Servicio')),
                ('Servicio', models.CharField(choices=[('UCI1', 'UCI1'), ('UCI2', 'UCI2'), ('UCIA', 'UCIA'), ('UCIP', 'UCIP'), ('UCIN', 'UCIN')], max_length=15, verbose_name='Servicio')),
                ('Habitacion', models.CharField(choices=[('BOX01', 'BOX01'), ('BOX02', 'BOX02')], max_length=15, verbose_name='Habitacion')),
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('MP', models.FloatField(null=True, verbose_name='MP')),
                ('VT', models.FloatField(null=True, verbose_name='VT')),
                ('PEEP', models.FloatField(null=True, verbose_name='PEEP')),
                ('RR', models.FloatField(null=True, verbose_name='RR')),
                ('PPlato', models.FloatField(null=True, verbose_name='PPlato')),
                ('PPeak', models.FloatField(null=True, verbose_name='PPeak')),
                ('propuestas', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'Mapeo',
            },
        ),
        migrations.AlterField(
            model_name='mapas',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='ID'),
        ),
    ]
