# Generated by Django 4.0.3 on 2022-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0038_mapeo_alter_mapas_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeo',
            name='titulo',
        ),
    ]
