# Generated by Django 4.0.3 on 2022-03-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0039_remove_mapeo_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeo',
            name='propuestas',
        ),
    ]
