# Generated by Django 4.0.3 on 2022-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0041_mapeo_liked_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapas',
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Ninguna me convence', 'Ninguna me convence'), ('Bajar VT', 'Bajar VT'), ('Bajar PEEP', 'Bajer PEEP'), ('Bajar RR', 'Bajar RR')], default='Like', max_length=25),
        ),
    ]
