# Generated by Django 4.0.3 on 2022-03-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0043_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='mapa',
        ),
        migrations.DeleteModel(
            name='Mapeo',
        ),
    ]
