# Generated by Django 4.0.3 on 2022-03-11 18:30

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UCI_App', '0044_remove_like_mapa_delete_mapeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='ID')),
                ('Centros', models.CharField(blank=True, choices=[('VH', 'VH'), ('JX', 'JX')], max_length=15, verbose_name='Servicio')),
                ('Servicio', models.CharField(choices=[('UCI1', 'UCI1'), ('UCI2', 'UCI2'), ('UCIA', 'UCIA'), ('UCIP', 'UCIP'), ('UCIN', 'UCIN')], max_length=15, verbose_name='Servicio')),
                ('Habitacion', models.CharField(choices=[('BOX01', 'BOX01'), ('BOX02', 'BOX02')], max_length=15, verbose_name='Habitacion')),
                ('MP', models.FloatField(null=True, verbose_name='MP')),
                ('VT', models.FloatField(null=True, verbose_name='VT')),
                ('PEEP', models.FloatField(null=True, verbose_name='PEEP')),
                ('RR', models.FloatField(null=True, verbose_name='RR')),
                ('PPlato', models.FloatField(null=True, verbose_name='PPlato')),
                ('PPeak', models.FloatField(null=True, verbose_name='PPeak')),
                ('NumID', models.IntegerField(null=True, verbose_name='NumID')),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo',
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
