# Generated by Django 4.0.3 on 2022-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0046_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeo',
            name='Centros',
            field=models.CharField(blank=True, choices=[('VH', 'VH'), ('JX', 'JX')], max_length=15, verbose_name='Centro'),
        ),
    ]
