# Generated by Django 4.0.3 on 2022-03-14 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UCI_App', '0048_like_opcion1_like_opcion2_like_opcion3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPropuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Ninguna me convence', 'Ninguna me convence'), ('Bajar VT', 'Bajar VT'), ('Bajar PEEP', 'Bajer PEEP'), ('Bajar RR', 'Bajar RR')], default='No me convence', max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='mapeo',
            old_name='liked',
            new_name='Propuestas',
        ),
        migrations.RemoveField(
            model_name='mapeo',
            name='PEEPBajado',
        ),
        migrations.RemoveField(
            model_name='mapeo',
            name='RRBajado',
        ),
        migrations.RemoveField(
            model_name='mapeo',
            name='VTBajado',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='rpropuestas',
            name='mapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UCI_App.mapeo'),
        ),
        migrations.AddField(
            model_name='rpropuestas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
