# Generated by Django 4.0.3 on 2022-03-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0049_rpropuestas_rename_liked_mapeo_propuestas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propuestas',
        ),
    ]
