# Generated by Django 4.0.3 on 2022-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0052_categoria_mapeo_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
