# Generated by Django 4.0.3 on 2022-03-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0053_alter_categoria_options_alter_cuenta_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
