# Generated by Django 4.0.3 on 2022-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0055_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosConectados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mapeo',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
