# Generated by Django 4.0.3 on 2022-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0056_usuariosconectados_alter_mapeo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpropuestas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
