# Generated by Django 4.0.3 on 2022-03-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0057_rpropuestas_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeo',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
