# Generated by Django 4.0.3 on 2022-03-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UCI_App', '0058_remove_mapeo_categorias_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
            },
        ),
    ]
