# Generated by Django 4.0.3 on 2022-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0059_numhits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numhits',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
