# Generated by Django 4.0.3 on 2022-03-31 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0061_conexiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpropuestas',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 23, 57, 13, 157985)),
        ),
    ]
