# Generated by Django 4.0.3 on 2022-03-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCI_App', '0062_alter_rpropuestas_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpropuestas',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
